const devPath = "/assets/images"
const gitPath = "https://brook072.github.io/2022JavaScriptTrainingWeek8/assets/images"

module.exports = {
  content: ["./app/**/*.{html,ejs,js}"],
  theme: {
    container:{
      center: true,
      padding:{
        default: '0.75rem',
        '2xl':'13.3125rem',
      },
    },
    extend: {
      backgroundImage:{
        'banner': `url('${gitPath}/3ewLAKn.png')`,
        'cons-1': `url('${gitPath}/tR426y5.png')`,
        'cons-2': `url('${gitPath}/Fd2MiBb.png')`,
        'cons-3': `url('${gitPath}/5n1uTFh.png')`,
        'user-1': `url('${gitPath}/I9L7WOr.png')`,
        'user-2': `url('${gitPath}/CUFGfay.png')`,
        'user-3': `url('${gitPath}/8WwZsLS.png')`,
        'user-4': `url('${gitPath}/NycuPVy.png')`,
        'user-5': `url('${gitPath}/zdFOQIv.png')`,
        'user-6': `url('${gitPath}/W7fyzp2.png')`,
        'user-7': `url('${gitPath}/8O1cOnG.png')`,
        'user-8': `url('${gitPath}/C0NDvSA.png')`,
        'user-9': `url('${gitPath}/hUsTZDm.png')`,
        'user-10': `url('${gitPath}/3ako6QX.png')`,
        'comment-1': `url('${gitPath}/cXcOLhu.png')`,
        'comment-2': `url('${gitPath}/BefHmH2.png')`,
        'comment-3': `url('${gitPath}/3IATkJG.png')`,
        'comment-4': `url('${gitPath}/C0aYlUQ.png')`,
        'comment-5': `url('${gitPath}/bt1lsT2.png')`,
        'comment-6': `url('${gitPath}/JlGUkjl.png')`,
        'comment-7': `url('${gitPath}/kwIRna8.png')`,
        'comment-8': `url('${gitPath}/npA3DgP.png')`,
        'comment-9': `url('${gitPath}/xypuv56.png')`,
        'comment-10': `url('${gitPath}/mjA01Tk.png')`,
        'goods-1': `url('${gitPath}/oJb4G1d.png')`,
      },
      borderWidth: {
        '3': '3px',
      },
      colors:{
        'grey': '#B9B9B9',
        'light-grey': '#F8F8F8',
        'dark-grey': '#797979',
        'light-purple': '#6A33F8',
        'dark-purple': '#301E5F',
        'aluminium': '#818A91',
        'red': '#FF0000',
        'dark-red' : '#C44021',
      },
      fontSize: {
        '7': '1.75rem',
      },
      spacing:{
        '30%': '30%',
        0.75: '0.1875rem',
        1.75: '0.4375rem',
        6.5: '1.625rem',
        13: '3.25rem',
        14: '3.5rem',
        15: '3.75rem',
        17: '4.25rem',
        18: '4.5rem',
        27: '6.125rem',
        29: '7.25rem',
        35: '8.75rem',
        43: '10.75rem',
        64: '16rem',
        87: '21.75rem',
        75.5: '18.875rem',
        102: '25.5rem',
        105: '26.25rem',
        110: '27.5rem',
        120: '30rem',
      },
      lineHeight: {
        'extra-loose': '3',
      },
      borderRadius: {
        0.5:'50%',
      },
    },
    fontFamily: {
      'Geeza': ['Geeza pro'],
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}